### ISSUE TITLE
[httpsync] fail to install on windows 

### ISSUE THREAD

**Issue by pipiscrew** [fengmk2/node-curl#16]
1 D:\node\node.exe "D:\node\.\node_modules\npm\bin\npm-cli.js" install httpsync
npm http GET https://registry.npmjs.org/httpsync
npm http 304 https://registry.npmjs.org/httpsync

> httpsync@0.0.8 install D:\node\node_modules\httpsync
> sh build.sh

'sh' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! httpsync@0.0.8 install: `sh build.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the httpsync@0.0.8 install script.
npm ERR! This is most likely a problem with the httpsync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     sh build.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls httpsync
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "D:\node\\node.exe" "D:\node\node_modules\npm\bin\npm-cli.js" "install" "httpsync"
npm ERR! cwd D:\node
npm ERR! node -v v0.10.23
npm ERR! npm -v 1.3.17
npm ERR! code ELIFECYCLE

**Comment by quirijnslings** [comment]
I have the same issue, is there any progress to report?
I tried to install it through Cygwin, but that gives another problem: the build.sh cannot find node-gyp even though it is installed on my system.

**Comment by raeesaa** [comment]
pipiscrew: Were you able to install this on windows?

**Comment by pipiscrew** [comment]
no never worked.. I found an alternative.. thanks
