### ISSUE TITLE
Way to handle errors?

### ISSUE THREAD

**Issue by raeesaa** [fengmk2/node-curl#20]
I would like to thank all the contributors for this great library. 

I just wanted to know if there exists a way for handling errors like remote server is down or connection timed out. I can see these errors in logs

`Error: Couldn't connect to server`

`Error: Timeout was reached`

 but I would like to handle them in code and I haven't found a way to do that yet.

Thanks.

**Comment by lincolnlemos** [comment]
Need help with this to...

"Couldn't resolve host name" broken my code sometimes ;/

**Comment by fengmk2** [comment]
This module no longer work, please use https://github.com/node-modules/urllib-sync instead.
