### ISSUE TITLE
无法请求同一进程的http server

### ISSUE THREAD

**Issue by fengmk2** [fengmk2/node-curl#4]
测试代码:

``` js

var httpsync = require('../');
var http = require('http');

var app = http.createServer(function (req, res) {
  console.log(req.url, req.headers);
  req.on('end', function () {
    res.end('hello world');
  });
});

app.listen(0, function () {
  var url = 'http://127.0.0.1:' + app.address().port;
  console.log('start to request: ' + url);
  var req = httpsync.get(url);
  var res = req.end();
  console.log(res);
  process.exit(0);
});
```

进程卡住了。

**Comment by zcbenz** [comment]
httpsync.end()执行时整个线程都会block住直到函数结束，主线程block时将无法进入事件循环，也就无法响应其它请求，于是httpsync.end()就会一直等下去。也就是说httpsync.end()等待进程进入主循环来响应请求，但同时进程又在等待httpsync.end()结束以便进入主循环，有些类似于dead lock。

对于同步阻塞的函数调用来说，这种行为是正确而且可以预料的。

**Comment by fengmk2** [comment]
## 厄，狂然大悟 #fixed

MK2, FaWave, Net4Team ☺nodejs
TEL: 18668079069
Github: https://github.com/fengmk2
微博: @Python发烧友
Twitter: @fengmk2
CNode: http://cnodejs.org/user/suqian
Blog: http://fengmk2.github.com/
