### ISSUE TITLE
How to post a form with Content-Type=application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by ylmw0131** [fengmk2/node-curl#6]
req = HTTPS_SYNC.request
                                 (
                                        {
                                            protocol: 'https',
                                            host: 'target.com',
                                            port: 443,
                                            path: '/login.aspx',
                                            method: 'POST',
                                            rejectUnauthorized: false,
                                            requestCert: true,
                                            agent: false,
                                            headers: {
                                                'Cookie': this.cookie,
                                                'Content-Type': 'application/x-www-form-urlencoded',
                                                'Content-Length': loginFormData.length
                                            }
                                        }
                                );
                                req.write(loginFormData);
                                res = req.end();

But failed on res.end(); seems it is timeout.

Please check, thank you

**Comment by fengmk2** [comment]
This module no longer work, please use https://github.com/node-modules/urllib-sync instead.
