### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by CSilivestru** [fengmk2/node-curl#8]
I tried to install the package through npm install and it failed. The is the error output produced in the npm-debug.log. Any ideas how to resolve this? I'm running Mountain Lion :-). Thanks!!
error httpsync@0.0.7 install: `sh build.sh`
172 error `sh "-c" "sh build.sh"` failed with 1
173 error Failed at the httpsync@0.0.7 install script.
173 error This is most likely a problem with the httpsync package,
173 error not with npm itself.
173 error Tell the author that this fails on your system:
173 error     sh build.sh
173 error You can get their info via:
173 error     npm owner ls httpsync
173 error There is likely additional logging output above.
174 error System Darwin 12.2.0
175 error command "node" "/usr/local/bin/npm" "install" "httpsync@0.0.7"
176 error cwd /Users/Chris/Development/Factory/Supernova
177 error node -v v0.8.16
178 error npm -v 1.1.70
179 error code ELIFECYCLE
180 verbose exit [ 1, true ]

**Comment by CSilivestru** [comment]
I should mention that reverting back to 0.0.6 produces no error -- hope that helps!

**Comment by EndangeredMassa** [comment]
Same thing happened to me. Install 0.0.6 did not produce a failure.

**Comment by weakish** [comment]
I got this error:

```
Traceback (most recent call last):
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
AttributeError: 'module' object has no attribute 'script_main'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/no
de_modules/node-gyp/lib/configure.js:337:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.
js:797:12)
```

**Comment by fengmk2** [comment]
This module no longer work, please use https://github.com/node-modules/urllib-sync instead.
